### ISSUE TITLE
[deven website] Implement Blog Post Page Component

### ISSUE THREAD

**Issue by GiordanaFurquim** [deven-org/deven-website#57] opened 2023-04-18 14:37 UTC
# Description

TBD

# Acceptance Criteria

- [ ] 1
- [ ] 2
- [ ] 3

# Technical Approach

To be defined by the Dev team

# Risks

- [ ] 1
- [ ] 2
- [ ] 3

##  Related tickets

📌

**Comment by remmycat** [comment] 2023-09-25 10:34
This issue seems to be a duplicate of #77 (or the other way around, but that one is where the work happened)

**Closed by remmycat** 2023-09-25 10:34 UTC
Labels: 💌 release 1.1., 🌐 website
