### ISSUE TITLE
[deven website] Implement Latest News Component SCSS Styles

### ISSUE THREAD

**Issue by GiordanaFurquim** [deven-org/deven-website#55] opened 2023-04-18 13:18 UTC
# Description

TBD

# Acceptance Criteria

- [ ] 1
- [ ] 2
- [ ] 3

# Technical Approach

To be defined by the Dev Team

# Risks

- [ ] 1
- [ ] 2
- [ ] 3

##  Related tickets

📌

**Comment by remmycat** [comment] 2023-09-25 10:30
This seems to be a duplicate of #54 (I don't see why we would need an additional issue)

**Closed by remmycat** 2023-09-25 10:30 UTC
Labels: 💌 release 1.1., 🌐 website
